
Metrics/MethodLength:
  Max: 200

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 50

Naming/FileName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false
